### ISSUE TITLE
Вопрос про корректность использования метода

### ISSUE THREAD

**Issue by Lagunov-PRO** [Lagunov-PRO/HW05_Reverse_Zodiac#1]
@coursar
Подскажите, корректно ли вот так использовать метод, переопределяя пользовательский ввод?
Или использовать промежуточную переменную?
Нужно для сравнения со своим списком.

https://github.com/Lagunov-PRO/HW05_Reverse_Zodiac/blob/c739fb58be56eec8846d33ea009a649b2048ed10/app/lib.py#L8

**Comment by coursar** [comment]
корректно, многие так делают для сокращения кода и чтобы не придумывать новое имя переменной
